skip CAA check if Let's Encrypt is not used

diff --git a/zinstaller b/zinstaller
--- a/zinstaller
+++ b/zinstaller
@@ -275,8 +275,8 @@ apt-get -qq update
 # Get Ubuntu Version
 version=$(lsb_release -d | awk -F" " '{print $3}' | cut -c 1-5)
 
-if [ $(dig +short type257 $(hostname --d) | grep "letsencrypt.org" | grep -v "issuewild" | grep "issue" | wc -l) -eq 1 ]; then 
-   if [ "$LETSENCRYPT" != "${LETSENCRYPT#[Yy]}" ] ;then # this grammar (the #[] operator) means that the variable $answer where any Y or y in 1st position will be dropped if they exist.
+if [ "$LETSENCRYPT" != "${LETSENCRYPT#[Yy]}" ] ;then # this grammar (the #[] operator) means that the variable $answer where any Y or y in 1st position will be dropped if they exist.
+   if [ $(dig +short type257 $(hostname --d) | grep "letsencrypt.org" | grep -v "issuewild" | grep "issue" | wc -l) -eq 1 ]; then   
       echo "Installing certbot"
       apt install -y python3 python3-venv libaugeas0
       python3 -m venv /opt/certbot/
@@ -301,11 +301,11 @@ su - zimbra -c '/opt/zimbra/bin/zmcertmgr deploycrt comm "/etc/letsencrypt/live/
 rm -f "/etc/letsencrypt/live/$(hostname --fqdn)/chainZimbra.pem"
 EOF
       chmod +rx /usr/local/sbin/letsencrypt-zimbra
+   else 
+      echo "CAA record for your domain cannot be found, you should add it first, example for bind:"
+      echo "@			CAA     0 issue \"letsencrypt.org\""
+      exit 1
    fi
-else 
-   echo "CAA record for your domain cannot be found, you should add it first, example for bind:"
-   echo "@			CAA     0 issue \"letsencrypt.org\""
-   exit 1
 fi
 
 #other updates
